#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_ReplayEditorPostProcessVolume_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.InitAllSettings
struct AReplayEditorPostProcessVolume_C_InitAllSettings_Params
{
};

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.SetVignette
struct AReplayEditorPostProcessVolume_C_SetVignette_Params
{
	bool*                                              IsEnable;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             Intensity;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.SetBloom
struct AReplayEditorPostProcessVolume_C_SetBloom_Params
{
	bool*                                              IsEnable;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             Intensity;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.SetColorGrading
struct AReplayEditorPostProcessVolume_C_SetColorGrading_Params
{
	bool*                                              IsEnable;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	class UTexture**                                   LUT;                                                      // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             LUTIntensity;                                             // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.SetDof
struct AReplayEditorPostProcessVolume_C_SetDof_Params
{
	bool*                                              IsEnable;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	class FString*                                     DofMethod;                                                // (Parm, ZeroConstructor)
	float*                                             DofFocalRegion;                                           // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofFocalDistance;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofNearTransitionRegion;                                  // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofFarTransitionRegion;                                   // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofBokehScale;                                            // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofBokehMaxSize;                                          // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofGaussianNearBlurSize;                                  // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             DofGaussianFarBlurSize;                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.SetAutoExposure
struct AReplayEditorPostProcessVolume_C_SetAutoExposure_Params
{
	bool*                                              IsEnable;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C.UserConstructionScript
struct AReplayEditorPostProcessVolume_C_UserConstructionScript_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
