#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_ReplayEditorPostProcessVolume_structs.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C
// 0x0010 (0x03F0 - 0x03E0)
class AReplayEditorPostProcessVolume_C : public AActor
{
public:
	class UPostProcessComponent*                       PostProcess;                                              // 0x03E0(0x0008) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class USceneComponent*                             DefaultSceneRoot;                                         // 0x03E8(0x0008) (BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static auto ptr = UObject::FindClass("BlueprintGeneratedClass ReplayEditorPostProcessVolume.ReplayEditorPostProcessVolume_C");
		return ptr;
	}


	void InitAllSettings();
	void SetVignette(bool* IsEnable, float* Intensity);
	void SetBloom(bool* IsEnable, float* Intensity);
	void SetColorGrading(bool* IsEnable, class UTexture** LUT, float* LUTIntensity);
	void SetDof(bool* IsEnable, class FString* DofMethod, float* DofFocalRegion, float* DofFocalDistance, float* DofNearTransitionRegion, float* DofFarTransitionRegion, float* DofBokehScale, float* DofBokehMaxSize, float* DofGaussianNearBlurSize, float* DofGaussianFarBlurSize);
	void SetAutoExposure(bool* IsEnable);
	void UserConstructionScript();
};


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
