#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_Basic.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// UserDefinedEnum BP_Console_Type.BP_Console_Type
enum class EBP_Console_Type : uint8_t
{
	BP_Console_Type__NewEnumerator0 = 0,
	BP_Console_Type__NewEnumerator1 = 1,
	BP_Console_Type__NewEnumerator2 = 2,
	BP_Console_Type__NewEnumerator3 = 3,
	BP_Console_Type__BP_Console_MAX = 4
};



}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
