#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_GamepadOptionDescWidget_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_GamepadOptionDescWidget.BP_GamepadOptionDescWidget_C.SetCrosshairPreviewVisibility
struct UBP_GamepadOptionDescWidget_C_SetCrosshairPreviewVisibility_Params
{
	bool                                               bVisible;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function BP_GamepadOptionDescWidget.BP_GamepadOptionDescWidget_C.SetCrosshairPreviewColor
struct UBP_GamepadOptionDescWidget_C_SetCrosshairPreviewColor_Params
{
	struct FLinearColor                                NewParam;                                                 // (Parm, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
