// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_TracerManager_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function TslGame.TslTracerManager.Multi_AddInstance
// (Net, Native, Event, NetMulticast)
// Parameters:
// struct FTracerSimulationServerData* InTracerData                   (ConstParm, Parm, ReferenceParm)

void ABP_TracerManager_C::Multi_AddInstance(struct FTracerSimulationServerData* InTracerData)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.TslTracerManager.Multi_AddInstance");

	ABP_TracerManager_C_Multi_AddInstance_Params params;
	params.InTracerData = InTracerData;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
