#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_ConstraintSlotOwnerItemIconWidget_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_ConstraintSlotOwnerItemIconWidget.BP_ConstraintSlotOwnerItemIconWidget_C.UpdateIcon
struct UBP_ConstraintSlotOwnerItemIconWidget_C_UpdateIcon_Params
{
	class UItem**                                      Item;                                                     // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function BP_ConstraintSlotOwnerItemIconWidget.BP_ConstraintSlotOwnerItemIconWidget_C.Construct
struct UBP_ConstraintSlotOwnerItemIconWidget_C_Construct_Params
{
};

// Function BP_ConstraintSlotOwnerItemIconWidget.BP_ConstraintSlotOwnerItemIconWidget_C.ExecuteUbergraph_BP_ConstraintSlotOwnerItemIconWidget
struct UBP_ConstraintSlotOwnerItemIconWidget_C_ExecuteUbergraph_BP_ConstraintSlotOwnerItemIconWidget_Params
{
	int*                                               EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
