// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_GamepadOptionGraphic_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function TslGame.TslGamepadOptionGraphic.OnStepperChanged
// (Final, Native)
// Parameters:
// class UTslGamepadStepperWidget** Widget                         (Parm, ZeroConstructor, InstancedReference, IsPlainOldData)

void UBP_GamepadOptionGraphic_C::OnStepperChanged(class UTslGamepadStepperWidget** Widget)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.TslGamepadOptionGraphic.OnStepperChanged");

	UBP_GamepadOptionGraphic_C_OnStepperChanged_Params params;
	params.Widget = Widget;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
