#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_GamepadOptionControl_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function TslGame.TslGamepadOptionContentsWidget.HandleGamepadUpOfChild
struct UBP_GamepadOptionControl_C_HandleGamepadUpOfChild_Params
{
	TScriptInterface<class UTslNaviWidgetInterface>*   Widget;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function TslGame.TslGamepadOptionContentsWidget.HandleGamepadDownOfChild
struct UBP_GamepadOptionControl_C_HandleGamepadDownOfChild_Params
{
	TScriptInterface<class UTslNaviWidgetInterface>*   Widget;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function TslGame.TslGamepadOptionContentsWidget.HandleFocusReceivedOfChild
struct UBP_GamepadOptionControl_C_HandleFocusReceivedOfChild_Params
{
	TScriptInterface<class UTslNaviWidgetInterface>*   Widget;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
