#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_ComboBoxOption_structs.hpp"

namespace SDK
{
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
