// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_TslBaseLobbySceneTravel_CameraMove_Fast_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.UserConstructionScript
// (Event)

void ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C::UserConstructionScript()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.UserConstructionScript");

	ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C_UserConstructionScript_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.CameraMove__FinishedFunc
// ()

void ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C::CameraMove__FinishedFunc()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.CameraMove__FinishedFunc");

	ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C_CameraMove__FinishedFunc_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.CameraMove__UpdateFunc
// ()

void ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C::CameraMove__UpdateFunc()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.CameraMove__UpdateFunc");

	ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C_CameraMove__UpdateFunc_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.OnStartTravel
// (Event)

void ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C::OnStartTravel()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.OnStartTravel");

	ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C_OnStartTravel_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.ExecuteUbergraph_BP_TslBaseLobbySceneTravel_CameraMove_Fast
// ()
// Parameters:
// int*                           EntryPoint                     (Parm, ZeroConstructor, IsPlainOldData)

void ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C::ExecuteUbergraph_BP_TslBaseLobbySceneTravel_CameraMove_Fast(int* EntryPoint)
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_TslBaseLobbySceneTravel_CameraMove_Fast.BP_TslBaseLobbySceneTravel_CameraMove_Fast_C.ExecuteUbergraph_BP_TslBaseLobbySceneTravel_CameraMove_Fast");

	ABP_TslBaseLobbySceneTravel_CameraMove_Fast_C_ExecuteUbergraph_BP_TslBaseLobbySceneTravel_CameraMove_Fast_Params params;
	params.EntryPoint = EntryPoint;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
