#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_CrosshairColorPaletteWidget_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_CrosshairColorPaletteWidget.BP_CrosshairColorPaletteWidget_C.OnPrepass_1
struct UBP_CrosshairColorPaletteWidget_C_OnPrepass_1_Params
{
	class UWidget**                                    BoundWidget;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function BP_CrosshairColorPaletteWidget.BP_CrosshairColorPaletteWidget_C.Apply
struct UBP_CrosshairColorPaletteWidget_C_Apply_Params
{
};

// Function BP_CrosshairColorPaletteWidget.BP_CrosshairColorPaletteWidget_C.Init
struct UBP_CrosshairColorPaletteWidget_C_Init_Params
{
	class UPresetColorComboBoxWidget_C**               PresetColorComboBox;                                      // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function BP_CrosshairColorPaletteWidget.BP_CrosshairColorPaletteWidget_C.SetToDefault
struct UBP_CrosshairColorPaletteWidget_C_SetToDefault_Params
{
};

// Function BP_CrosshairColorPaletteWidget.BP_CrosshairColorPaletteWidget_C.IsChanged
struct UBP_CrosshairColorPaletteWidget_C_IsChanged_Params
{
	bool                                               res;                                                      // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
