#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_KeyGuideTabWidget_structs.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// WidgetBlueprintGeneratedClass KeyGuideTabWidget.KeyGuideTabWidget_C
// 0x0000 (0x0418 - 0x0418)
class UKeyGuideTabWidget_C : public UTslTabSelectorWidget
{
public:

	static UClass* StaticClass()
	{
		static auto ptr = UObject::FindClass("WidgetBlueprintGeneratedClass KeyGuideTabWidget.KeyGuideTabWidget_C");
		return ptr;
	}


	void UpdateIndexTo(int* NewIndex);
	void RotateRight();
	void RotateLeft();
	void ResetSelector();
};


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
