#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_ReplayCurvedSpline_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_ReplayCurvedSpline.BP_ReplayCurvedSpline_C.GenFreeCamSections
struct ABP_ReplayCurvedSpline_C_GenFreeCamSections_Params
{
};

// Function BP_ReplayCurvedSpline.BP_ReplayCurvedSpline_C.ClearAllPoints
struct ABP_ReplayCurvedSpline_C_ClearAllPoints_Params
{
};

// Function BP_ReplayCurvedSpline.BP_ReplayCurvedSpline_C.SetPoints
struct ABP_ReplayCurvedSpline_C_SetPoints_Params
{
};

// Function BP_ReplayCurvedSpline.BP_ReplayCurvedSpline_C.SetMeshAndMaterial
struct ABP_ReplayCurvedSpline_C_SetMeshAndMaterial_Params
{
};

// Function BP_ReplayCurvedSpline.BP_ReplayCurvedSpline_C.GetInterPoint
struct ABP_ReplayCurvedSpline_C_GetInterPoint_Params
{
	float                                              ALPHA;                                                    // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                PrevIdx;                                                  // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                NextIdx;                                                  // (Parm, ZeroConstructor, IsPlainOldData)
	struct FVector                                     Location;                                                 // (Parm, OutParm, IsPlainOldData)
	struct FRotator                                    Rotation;                                                 // (Parm, OutParm, IsPlainOldData)
};

// Function BP_ReplayCurvedSpline.BP_ReplayCurvedSpline_C.UserConstructionScript
struct ABP_ReplayCurvedSpline_C_UserConstructionScript_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
