// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_CarePackageItemSlotWidget_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.IsFocusable
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::IsFocusable()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.IsFocusable");

	UCarePackageItemSlotWidget_C_IsFocusable_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputLB
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputLB()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputLB");

	UCarePackageItemSlotWidget_C_InputLB_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputLT
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputLT()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputLT");

	UCarePackageItemSlotWidget_C_InputLT_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputRB
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputRB()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputRB");

	UCarePackageItemSlotWidget_C_InputRB_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputRT
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputRT()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputRT");

	UCarePackageItemSlotWidget_C_InputRT_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetFocusingChildWidget
// (Event)
// Parameters:
// class UUserWidget*             ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

class UUserWidget* UCarePackageItemSlotWidget_C::GetFocusingChildWidget()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetFocusingChildWidget");

	UCarePackageItemSlotWidget_C_GetFocusingChildWidget_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputA
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputA()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputA");

	UCarePackageItemSlotWidget_C_InputA_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputB
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputB()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputB");

	UCarePackageItemSlotWidget_C_InputB_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputX
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputX()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputX");

	UCarePackageItemSlotWidget_C_InputX_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputY
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::InputY()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.InputY");

	UCarePackageItemSlotWidget_C_InputY_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetDownWidget
// (Event)
// Parameters:
// class UUserWidget*             ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

class UUserWidget* UCarePackageItemSlotWidget_C::GetDownWidget()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetDownWidget");

	UCarePackageItemSlotWidget_C_GetDownWidget_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetLeftWidget
// (Event)
// Parameters:
// class UUserWidget*             ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

class UUserWidget* UCarePackageItemSlotWidget_C::GetLeftWidget()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetLeftWidget");

	UCarePackageItemSlotWidget_C_GetLeftWidget_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetRightWidget
// (Event)
// Parameters:
// class UUserWidget*             ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

class UUserWidget* UCarePackageItemSlotWidget_C::GetRightWidget()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetRightWidget");

	UCarePackageItemSlotWidget_C_GetRightWidget_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetUpWidget
// (Event)
// Parameters:
// class UUserWidget*             ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

class UUserWidget* UCarePackageItemSlotWidget_C::GetUpWidget()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetUpWidget");

	UCarePackageItemSlotWidget_C_GetUpWidget_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Down
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::Down()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Down");

	UCarePackageItemSlotWidget_C_Down_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.IsFocus
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::IsFocus()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.IsFocus");

	UCarePackageItemSlotWidget_C_IsFocus_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Left
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::Left()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Left");

	UCarePackageItemSlotWidget_C_Left_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Right
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::Right()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Right");

	UCarePackageItemSlotWidget_C_Right_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetFocus
// (Event)
// Parameters:
// bool                           NewFocus                       (Parm, ZeroConstructor, IsPlainOldData)
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::SetFocus(bool NewFocus)
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetFocus");

	UCarePackageItemSlotWidget_C_SetFocus_Params params;
	params.NewFocus = NewFocus;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Up
// (Event)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool UCarePackageItemSlotWidget_C::Up()
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.Up");

	UCarePackageItemSlotWidget_C_Up_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetSlotItem
// ()
// Parameters:
// TScriptInterface<class USlotInterface> SlotItem                       (Parm, OutParm, ZeroConstructor, IsPlainOldData)

void UCarePackageItemSlotWidget_C::GetSlotItem(TScriptInterface<class USlotInterface>* SlotItem)
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetSlotItem");

	UCarePackageItemSlotWidget_C_GetSlotItem_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	if (SlotItem != nullptr)
		*SlotItem = params.SlotItem;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetSlotContainer
// ()
// Parameters:
// TScriptInterface<class USlotContainerInterface> SlotContainer                  (Parm, OutParm, ZeroConstructor, IsPlainOldData)

void UCarePackageItemSlotWidget_C::GetSlotContainer(TScriptInterface<class USlotContainerInterface>* SlotContainer)
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.GetSlotContainer");

	UCarePackageItemSlotWidget_C_GetSlotContainer_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	if (SlotContainer != nullptr)
		*SlotContainer = params.SlotContainer;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetItemCount
// ()
// Parameters:
// int                            ItemCount                      (Parm, ZeroConstructor, IsPlainOldData)

void UCarePackageItemSlotWidget_C::SetItemCount(int ItemCount)
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetItemCount");

	UCarePackageItemSlotWidget_C_SetItemCount_Params params;
	params.ItemCount = ItemCount;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetItemIcon
// ()
// Parameters:
// class UTexture**               ItemIcon                       (Parm, ZeroConstructor, IsPlainOldData)

void UCarePackageItemSlotWidget_C::SetItemIcon(class UTexture** ItemIcon)
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetItemIcon");

	UCarePackageItemSlotWidget_C_SetItemIcon_Params params;
	params.ItemIcon = ItemIcon;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetItemName
// ()
// Parameters:
// struct FText                   ItemName                       (Parm)

void UCarePackageItemSlotWidget_C::SetItemName(const struct FText& ItemName)
{
	static auto fn = UObject::FindObject<UFunction>("Function CarePackageItemSlotWidget.CarePackageItemSlotWidget_C.SetItemName");

	UCarePackageItemSlotWidget_C_SetItemName_Params params;
	params.ItemName = ItemName;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
