// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_TslCaptureLobby_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Backslash_K2Node_InputKeyEvent_26
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Backslash_K2Node_InputKeyEvent_26(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Backslash_K2Node_InputKeyEvent_26");

	ATslCaptureLobby_C_InpActEvt_Backslash_K2Node_InputKeyEvent_26_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Left_K2Node_InputKeyEvent_25
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Left_K2Node_InputKeyEvent_25(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Left_K2Node_InputKeyEvent_25");

	ATslCaptureLobby_C_InpActEvt_Left_K2Node_InputKeyEvent_25_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Left_K2Node_InputKeyEvent_24
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Left_K2Node_InputKeyEvent_24(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Left_K2Node_InputKeyEvent_24");

	ATslCaptureLobby_C_InpActEvt_Left_K2Node_InputKeyEvent_24_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Right_K2Node_InputKeyEvent_23
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Right_K2Node_InputKeyEvent_23(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Right_K2Node_InputKeyEvent_23");

	ATslCaptureLobby_C_InpActEvt_Right_K2Node_InputKeyEvent_23_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Right_K2Node_InputKeyEvent_22
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Right_K2Node_InputKeyEvent_22(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Right_K2Node_InputKeyEvent_22");

	ATslCaptureLobby_C_InpActEvt_Right_K2Node_InputKeyEvent_22_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Up_K2Node_InputKeyEvent_21
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Up_K2Node_InputKeyEvent_21(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Up_K2Node_InputKeyEvent_21");

	ATslCaptureLobby_C_InpActEvt_Up_K2Node_InputKeyEvent_21_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Up_K2Node_InputKeyEvent_20
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Up_K2Node_InputKeyEvent_20(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Up_K2Node_InputKeyEvent_20");

	ATslCaptureLobby_C_InpActEvt_Up_K2Node_InputKeyEvent_20_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Down_K2Node_InputKeyEvent_19
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Down_K2Node_InputKeyEvent_19(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Down_K2Node_InputKeyEvent_19");

	ATslCaptureLobby_C_InpActEvt_Down_K2Node_InputKeyEvent_19_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Down_K2Node_InputKeyEvent_18
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_Down_K2Node_InputKeyEvent_18(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_Down_K2Node_InputKeyEvent_18");

	ATslCaptureLobby_C_InpActEvt_Down_K2Node_InputKeyEvent_18_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_LeftBracket_K2Node_InputKeyEvent_17
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_LeftBracket_K2Node_InputKeyEvent_17(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_LeftBracket_K2Node_InputKeyEvent_17");

	ATslCaptureLobby_C_InpActEvt_LeftBracket_K2Node_InputKeyEvent_17_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_LeftBracket_K2Node_InputKeyEvent_16
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_LeftBracket_K2Node_InputKeyEvent_16(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_LeftBracket_K2Node_InputKeyEvent_16");

	ATslCaptureLobby_C_InpActEvt_LeftBracket_K2Node_InputKeyEvent_16_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_RightBracket_K2Node_InputKeyEvent_15
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_RightBracket_K2Node_InputKeyEvent_15(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_RightBracket_K2Node_InputKeyEvent_15");

	ATslCaptureLobby_C_InpActEvt_RightBracket_K2Node_InputKeyEvent_15_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_RightBracket_K2Node_InputKeyEvent_14
// ()
// Parameters:
// struct FKey*                   Key                            (Parm)

void ATslCaptureLobby_C::InpActEvt_RightBracket_K2Node_InputKeyEvent_14(struct FKey* Key)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.InpActEvt_RightBracket_K2Node_InputKeyEvent_14");

	ATslCaptureLobby_C_InpActEvt_RightBracket_K2Node_InputKeyEvent_14_Params params;
	params.Key = Key;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.ReceiveTick
// (Event)
// Parameters:
// float*                         DeltaSeconds                   (Parm, ZeroConstructor, IsPlainOldData)

void ATslCaptureLobby_C::ReceiveTick(float* DeltaSeconds)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.ReceiveTick");

	ATslCaptureLobby_C_ReceiveTick_Params params;
	params.DeltaSeconds = DeltaSeconds;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslCaptureLobby.TslCaptureLobby_C.ExecuteUbergraph_TslCaptureLobby
// ()
// Parameters:
// int*                           EntryPoint                     (Parm, ZeroConstructor, IsPlainOldData)

void ATslCaptureLobby_C::ExecuteUbergraph_TslCaptureLobby(int* EntryPoint)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslCaptureLobby.TslCaptureLobby_C.ExecuteUbergraph_TslCaptureLobby");

	ATslCaptureLobby_C_ExecuteUbergraph_TslCaptureLobby_Params params;
	params.EntryPoint = EntryPoint;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
