// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_LobbyCharacterMale_v2_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function TslGame.LobbyCharacter.SetLobbyCharacterAnimationType
// (Final, Native)
// Parameters:
// ELobbyCharacterAnimationType   NewLobbyCharacterAnimationType (Parm, ZeroConstructor, IsPlainOldData)

void ALobbyCharacterMale_v2_C::SetLobbyCharacterAnimationType(ELobbyCharacterAnimationType NewLobbyCharacterAnimationType)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.SetLobbyCharacterAnimationType");

	ALobbyCharacterMale_v2_C_SetLobbyCharacterAnimationType_Params params;
	params.NewLobbyCharacterAnimationType = NewLobbyCharacterAnimationType;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslGame.LobbyCharacter.OnMontageEnded
// (Final, Native)
// Parameters:
// class UAnimMontage**           Montage                        (Parm, ZeroConstructor, IsPlainOldData)
// bool*                          bInterrupted                   (Parm, ZeroConstructor, IsPlainOldData)

void ALobbyCharacterMale_v2_C::OnMontageEnded(class UAnimMontage** Montage, bool* bInterrupted)
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.OnMontageEnded");

	ALobbyCharacterMale_v2_C_OnMontageEnded_Params params;
	params.Montage = Montage;
	params.bInterrupted = bInterrupted;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function TslGame.LobbyCharacter.IsLogout
// (Final, Native)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool ALobbyCharacterMale_v2_C::IsLogout()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.IsLogout");

	ALobbyCharacterMale_v2_C_IsLogout_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function TslGame.LobbyCharacter.IsInCustomizationScene
// (Final, Native)
// Parameters:
// bool                           ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

bool ALobbyCharacterMale_v2_C::IsInCustomizationScene()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.IsInCustomizationScene");

	ALobbyCharacterMale_v2_C_IsInCustomizationScene_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function TslGame.LobbyCharacter.GetSlotId
// (Final, Native)
// Parameters:
// int                            ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

int ALobbyCharacterMale_v2_C::GetSlotId()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.GetSlotId");

	ALobbyCharacterMale_v2_C_GetSlotId_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function TslGame.LobbyCharacter.GetRankType
// (Final, Native)
// Parameters:
// ERatingRankType                ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

ERatingRankType ALobbyCharacterMale_v2_C::GetRankType()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.GetRankType");

	ALobbyCharacterMale_v2_C_GetRankType_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function TslGame.LobbyCharacter.GetNickName
// (Final, Native)
// Parameters:
// class FString                  ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm)

class FString ALobbyCharacterMale_v2_C::GetNickName()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.GetNickName");

	ALobbyCharacterMale_v2_C_GetNickName_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function TslGame.LobbyCharacter.GetNetId
// (Final, Native)
// Parameters:
// class FString                  ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm)

class FString ALobbyCharacterMale_v2_C::GetNetId()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.GetNetId");

	ALobbyCharacterMale_v2_C_GetNetId_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


// Function TslGame.LobbyCharacter.GetLobbyCharacterAnimationType
// (Final, Native)
// Parameters:
// ELobbyCharacterAnimationType   ReturnValue                    (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)

ELobbyCharacterAnimationType ALobbyCharacterMale_v2_C::GetLobbyCharacterAnimationType()
{
	static auto fn = UObject::FindObject<UFunction>("Function TslGame.LobbyCharacter.GetLobbyCharacterAnimationType");

	ALobbyCharacterMale_v2_C_GetLobbyCharacterAnimationType_Params params;

	auto flags = fn->FunctionFlags;
	fn->FunctionFlags |= 0x400;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;

	return params.ReturnValue;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
