#pragma once

// PUBG FULL SDK - Generated By Respecter (5.3.4.10 [04/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_TslLobby_Vikendi_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function TslLobby_Vikendi.TslLobby_Vikendi_C.ReceiveBeginPlay
struct ATslLobby_Vikendi_C_ReceiveBeginPlay_Params
{
};

// Function TslLobby_Vikendi.TslLobby_Vikendi_C.ExecuteUbergraph_TslLobby_Vikendi
struct ATslLobby_Vikendi_C_ExecuteUbergraph_TslLobby_Vikendi_Params
{
	int*                                               EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
