// PUBG FULL SDK - Generated By Respecter (5.3.4.11 [06/03/2019]) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "PUBG_BP_GamepadKeyGuideWidget_parameters.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.Construct
// (BlueprintCosmetic, Event)

void UBP_GamepadKeyGuideWidget_C::Construct()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.Construct");

	UBP_GamepadKeyGuideWidget_C_Construct_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.CustomEvent_1
// ()

void UBP_GamepadKeyGuideWidget_C::CustomEvent_1()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.CustomEvent_1");

	UBP_GamepadKeyGuideWidget_C_CustomEvent_1_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.CustomEvent_2
// ()

void UBP_GamepadKeyGuideWidget_C::CustomEvent_2()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.CustomEvent_2");

	UBP_GamepadKeyGuideWidget_C_CustomEvent_2_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.CustomEvent_3
// ()

void UBP_GamepadKeyGuideWidget_C::CustomEvent_3()
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.CustomEvent_3");

	UBP_GamepadKeyGuideWidget_C_CustomEvent_3_Params params;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.BndEvt__TabSelector_K2Node_ComponentBoundEvent_0_OnTabRotated__DelegateSignature
// ()
// Parameters:
// int*                           SelectedIndex                  (Parm, ZeroConstructor, IsPlainOldData)

void UBP_GamepadKeyGuideWidget_C::BndEvt__TabSelector_K2Node_ComponentBoundEvent_0_OnTabRotated__DelegateSignature(int* SelectedIndex)
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.BndEvt__TabSelector_K2Node_ComponentBoundEvent_0_OnTabRotated__DelegateSignature");

	UBP_GamepadKeyGuideWidget_C_BndEvt__TabSelector_K2Node_ComponentBoundEvent_0_OnTabRotated__DelegateSignature_Params params;
	params.SelectedIndex = SelectedIndex;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


// Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.ExecuteUbergraph_BP_GamepadKeyGuideWidget
// ()
// Parameters:
// int*                           EntryPoint                     (Parm, ZeroConstructor, IsPlainOldData)

void UBP_GamepadKeyGuideWidget_C::ExecuteUbergraph_BP_GamepadKeyGuideWidget(int* EntryPoint)
{
	static auto fn = UObject::FindObject<UFunction>("Function BP_GamepadKeyGuideWidget.BP_GamepadKeyGuideWidget_C.ExecuteUbergraph_BP_GamepadKeyGuideWidget");

	UBP_GamepadKeyGuideWidget_C_ExecuteUbergraph_BP_GamepadKeyGuideWidget_Params params;
	params.EntryPoint = EntryPoint;

	auto flags = fn->FunctionFlags;

	UObject::ProcessEvent(fn, &params);

	fn->FunctionFlags = flags;
}


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
